### PR TITLE
Range gentx

### PR DESCRIPTION
**Pull request by mrraange**

### CODE REVIEW

**Comment by faza** [comment]
@mrraange Can you please verify your chain-id. It should be `gitopia`. Getting the following error.

```
signature verification failed; please verify account number (0) and chain-id (gitopia): unauthorized
```

**Comment by mrraange** [comment]
@faza recreated

**Comment by faza** [comment]
@mrraange Still getting signature error. Did you pass the following flag in your gentx command?

```--chain-id gitopia```

**Comment by mrraange** [comment]
@faza yes 
Screenshot_7

**Comment by mrraange** [comment]
@faza recreated again

**Pull request merged**
