### PR TITLE
add NODEJUMPER gentx

### PR DESCRIPTION
**Pull request by vbloher**
added NODEJUMPER gentx json

### CODE REVIEW

**Comment by faza** [comment]
@vbloher Can you please verify your chain-id. It must be `gitopia`. Getting the following error.

```
signature verification failed; please verify account number (0) and chain-id (gitopia): unauthorized
```

**Comment by vbloher** [comment]
@faza checked twice. Сhain-id was set correctly to `gitopia`.
Tried to run `collect-gentxs` locally and didn't see any errors

**Comment by vbloher** [comment]
I'll do it all over again and update gentx

**Comment by vbloher** [comment]
@faza please check

**Pull request merged**
